tokenio/sdk-js

package.json, src/Util.js
Make testing emails include `+noverify` so they can be whitelisted
=> PL-1024: Make testing emails include +noverify so they can be whitelisted

src/sample/ProvisionDeviceSample.js, test/sample/ProvisionDeviceSample.spec.js
(and to log in using the hopefully-approved new key)
=> sample code to provision a device

package.json, src/main/TransferTokenBuilder.js
Check for bank field in source account of transfer tokens.
=> Appless checkout support

test/sample/GetAccessTokensSample.spec.js, test/sample/ReplaceAccessToken.spec.js, test/sample/ReplaceAndEndorseAccessToken.spec.js
Give them time to get indexed.
=> add some waitUntil between creating tokens and getAccessTokens

src/sample/PersistentlyCreateMemberSample.js
=> createMember sample code += useDefaultRecoveryRule

src/sample/RedeemAccessTokenSample.js, test/sample/RedeemAccessTokenSample.spec.js
https://github.com/tokenio/sdk-js/pull/68 was happy on my laptop
but sad on bamboo. I hope adding an "await" leads to joy everywhere.
=> like https://github.com/tokenio/sdk-js/pull/68 , but with an await

RELEASE_NOTES.md, package.json, src/config.json, src/sample/RedeemAccessTokenSample.js, src/security/engines/BrowserCryptoEngine.js, src/security/engines/BrowserKeyStore.js, src/security/engines/KeyStoreCryptoEngine.js, src/security/engines/MemoryCryptoEngine.js, src/security/engines/MemoryKeyStore.js, src/security/engines/UnsecuredFileCryptoEngine.js, src/security/engines/UnsecuredFileKeyStore.js, test/http/AuthHttpClient.spec.js, test/http/HttpClient.spec.js, test/security/FileSystemPromise.spec.js, test/security/engines/BrowserCryptoEngine.spec.js, test/security/engines/KeyStore.spec.js, test/security/engines/MemoryCryptoEngine.spec.js, yarn.lock
like https://github.com/tokenio/sdk-js/pull/67 , but without
using Object.values(), which our CI system did not like
=> keystore without using Object.values

package.json, src/http/AuthHttpClient.js, src/main/Member.js, src/main/TransferTokenBuilder.js
add receiptRequested setter on TransferTokenBuilder
=> add getter/setter for a member's receipt contact

package.json, src/main/TokenRequest.js
`const TokenRequest = Token.TokenRequest.create(payload).setEmail(email);`
=> Refactor TokenRequest

package.json, src/main/AccessTokenBuilder.js, src/main/TransferTokenBuilder.js
ref id will be mapped to fasterPayments reference information field which has a maximum length of 18 characters.
=> set ref id length to 18

package.json, src/security/Crypto.js, src/security/CryptoBrowser.js, src/security/engines/KeyStoreCryptoEngine.js, src/security/engines/ManualCryptoEngine.js, src/security/engines/README.md
=> Salty IE11

package.json, src/security/Crypto.js, src/security/CryptoBrowser.js, src/security/engines/KeyStoreCryptoEngine.js, src/security/engines/ManualCryptoEngine.js, src/security/engines/README.md
=> Revert "Salty IE11"

src/main/TransferTokenBuilder.js
Didn't bump the version because i thought this was a minor change(nothing really changed) and could be published with the next version
=> Added comment

package.json, src/http/AuthHttpClient.js, src/http/HttpClient.js, src/main/Member.js, src/main/Token.js, src/sample/TokenRequestUrlSample.js, test/sample/TokenRequestUrlSample.spec.js
1. Adding new get token request result call
2. Add token request id as a param in signTokenRequestState
=> add get token request result call

package.json, src/main/Member.js
Analog to createTransferToken, if the transfer status requires external auth, throw an error with the required details.
=> Support Legacy Transfer Flow

package.json, src/http/AuthHttpClient.js, src/main/Member.js, src/proto/gen/proto.js
Allows a partner to verify an affiliated TPP
=> RD-1024: Add VerifyAffiliate RPC

app/package.json, core/package.json, core/src/http/AuthHttpClient.js, tpp/package.json
Should fix the tests.
Basically we added a backend check to make sure the realm in the alias matches the realm in the `MemberAliasOperation`.
=> Fix realm in MemberAlaisOperation

app/package-lock.json, app/package.json, app/rollup.config.js
and unresolved dependencies as well as global variables warning from rollup
=> fix error on build uglify plugin error

app/package.json, app/src/main/TransferTokenBuilder.js, core/package.json, core/src/types.js, tpp/package.json
see https://github.com/tokenio/lib-proto/pull/411
=> Add bank id to the transfer endpoint

core/src/http/AuthHttpClient.js, core/src/main/Member.js, tpp/sample/GetTransactionsSample.js, tpp/src/main/Representable.js, tpp/src/main/TransferTokenRequestBuilder.js, tpp/test/sample/GetTransactionsSample.spec.js
Changes in getTransactions() for transactions filtering and added setSource() in TransferTokenRequestBuilder.
=> transactions filtering by date

tpp/package.json
This reverts commit 928e4c219363da277a7acc59d5a945165889e3f7.
=> Revert "bump tpp (#281)"

Release_Notes.md
Just 2 changes per DK:
1) Add "Last Updated" date
2) Changed version # to 1.0.2x
=> Updated release notes

app/package-lock.json, app/package.json, app/src/http/HttpClient.js, app/src/main/TokenClient.js, app/test/http/HttpClient.spec.js
An unauthenticated call for web-app to fetch the direct bank auth url. (The get bank auth url call is a tpp-authentication required one.)
=> add get direct auth url

tpp/package-lock.json, tpp/package.json, tpp/src/main/TokenClient.js
backward compatible for resource types.
=> resource type list backwards compatibility

app/package-lock.json, app/package.json, core/src/http/AuthContext.js, core/src/http/AuthHeader.js, core/src/http/AuthHttpClient.js, core/src/http/SecurityMetadataHeader.js, core/src/main/Member.js, core/src/types.js, tpp/package-lock.json, tpp/package.json, tpp/src/http/AuthHttpClient.js, tpp/src/main/Member.js
=> Revert "Modified the changes according to RD-2714 of sdk-java"

core/package-lock.json, core/package.json, core/src/types.js, tpp/package-lock.json, tpp/package.json, tpp/sample/WebhookSample.js, tpp/src/http/AuthHttpClient.js, tpp/src/main/Member.js, tpp/test/sample/WebhookSample.spec.js
=> add webhook endpoints

core/package.json, core/src/types.js, tpp/package-lock.json, tpp/package.json, tpp/src/main/TokenClient.js
=> Revert "added function to create member using type"

core/src/types.js, tpp/package-lock.json, tpp/package.json, tpp/src/main/TokenClient.js
=> Revert "add new memberType param for createMember"

app/package.json, core/package.json, core/src/http/HttpClient.js, core/src/main/TokenClient.js, tpp/package.json
=> Revert "APE-get banks"

core/package.json, core/src/http/AdditionalHeaders.js, core/src/http/HttpClient.js, core/src/main/TokenClient.js, tpp/package.json
Resolves an issue when fetching countries for a given member id that dev key was not included
=> SMP-3142 | allows headers to be added to the getBanksOrCountries method

tpp/package.json
Simply versions @token-io/tpp v1.0.67
=> SMP-3191 | @token-io/tpp v1.0.67

app/package.json, app/src/config.json, core/src/config.json, tpp/src/config.json
- Updated Configs with escrow environment values,
- Update package version
=> APE-2573 | Issues with frontend microservices on escrow

core/package.json
Content of this PR
--
- Updated Core Package version
=> APE-2573 | Update core version

app/package-lock.json, app/package.json, app/src/config.json, core/package-lock.json, core/package.json, core/src/config.json, tpp/package-lock.json, tpp/package.json, tpp/src/config.json
add configs for eks environment
=> SRE-2437-fix-confgig-env-eks

core/package.json, core/src/http/HttpClient.js
[APE-2796](https://tokenio.atlassian.net/browse/APE-2796)
[APE-2796]: https://tokenio.atlassian.net/browse/APE-2796?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> APE-2796 | Change query parameter for GET /banks to get all banks
